# Generated by Django 5.2 on 2026-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
