# Generated by Django 5.2 on 2026-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
