# Generated by Django 5.2 on 2026-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_current_login_profile_previous_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
