# Generated by Django 5.2 on 2026-08-21 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_topicvote'),
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='forum_conversation.post')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_link', to='forum_conversation.post')),
            ],
            options={
                'indexes': [models.Index(fields=['parent'], name='accounts_po_parent__db4b3c_idx')],
            },
        ),
    ]
